knp_gaufrette:
    stream_wrapper: ~
    adapters:
        document_adapter:
            aws_s3:
                service_id: df.aws_s3.client
                bucket_name: '%env(AWS_BUCKET_NAME)%'
                detect_content_type: true
    filesystems:
        document_fs:
            adapter:    document_adapter