vich_uploader:
    db_driver: orm
    storage: gaufrette

    mappings:
        file:
           uri_prefix: "%env(AWS_BASE_URL)%/%env(AWS_BUCKET_NAME)%"
           upload_destination: document_fs
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           directory_namer: App\Service\Shared\DirectoryNamerService
