#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /admin/login_check
api:
    type: annotation
    resource: ../src/Controller/Api
    prefix: /api/v1
    defaults: { _format: json }
api_admin:
    type: annotation
    resource: ../src/Controller/Admin
    prefix: /admin
    defaults: { _format: json }

default:
    path: /{path}
    methods: [GET]
    requirements:
        path: "^(?!api/).*" # api/ ile başlamayan bütün karakter dizileri
    defaults:
        _controller: App\Controller\DefaultController:defaultAction

